#!/usr/bin/env tsx
/**
 * Refresh liner note post images — standalone.
 *
 * The liner-notes pipeline runs this as Stage 5c on every scheduled run, but it
 * is also useful on its own: it needs no Anthropic API key, writes no new posts,
 * and costs nothing, so it can be run any time an image is reported broken
 * without paying for a generation cycle.
 *
 * Usage:
 *   npm run refresh:liner-note-images
 *   npm run refresh:liner-note-images -- --dry-run     # report, write nothing
 *   npm run refresh:liner-note-images -- --no-validate # skip HEAD checks (offline)
 *
 * See: https://github.com/mmorper/concerts/issues/252
 */

import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { refreshPostImages } from "./liner-notes/refresh-images.ts";
import type { LinerNotesData } from "../src/types/liner-notes.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, "..", "public", "data");
const LINER_NOTES_PATH = join(DATA_DIR, "liner-notes.json");

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const validate = !args.includes("--no-validate");

function readData<T>(file: string): T {
  return JSON.parse(readFileSync(join(DATA_DIR, file), "utf8")) as T;
}

async function main() {
  console.log("🖼️  Refreshing liner note images\n");
  if (dryRun) console.log("   Mode: dry-run (no files written)");
  if (!validate) console.log("   Mode: no-validate (skipping HEAD checks)");

  const data = readData<LinerNotesData>("liner-notes.json");
  const sources = {
    artistsMetadata: readData("artists-metadata.json"),
    artistsTopTracks: readData("artists-top-tracks.json"),
    venuesMetadata: readData("venues-metadata.json"),
  } as Parameters<typeof refreshPostImages>[1];

  const result = await refreshPostImages(data.posts, sources, { validate, verbose: true });

  console.log(
    `\n   ${result.posts} post${result.posts !== 1 ? "s" : ""} checked — ` +
      `${result.backfilled} ref backfilled, ${result.reresolved} re-resolved, ` +
      `${result.repaired} repaired, ${result.fellBack} to placeholder`
  );
  for (const dead of result.deadUrls) console.warn(`   ⚠️  Dead image URL — ${dead}`);

  if (result.changedSlugs.length === 0 && result.backfilled === 0) {
    console.log("\n✨ No changes.");
    return;
  }

  if (dryRun) {
    console.log(`\n✨ Dry run — ${result.changedSlugs.length} image(s) would change.`);
    return;
  }

  writeFileSync(LINER_NOTES_PATH, JSON.stringify(data, null, 2));
  console.log(`\n✓ Written: public/data/liner-notes.json`);
  console.log(
    "  Note: OG cards for changed posts are regenerated by the liner-notes pipeline;" +
      " run it if the images below are used as social previews."
  );
  for (const slug of result.changedSlugs) console.log(`   • ${slug}`);
}

main().catch((err) => {
  console.error("Refresh failed:", err);
  process.exit(1);
});
